name: POIDE E
on:
  schedule:
    - cron: '4-59/5 * * * *'
  workflow_dispatch:
permissions:
  contents: write
  pages: write

jobs:
  run:
    uses: ./.github/workflows/poide-run.yml
    secrets: inherit
